frase = 'Estruturas de Dados em Python'
maiuscula = frase.upper()
print(maiuscula)
pesquisa_frase = frase.find('Dados')
print(pesquisa_frase)
nova_frase = frase.replace('Python', 'Java')
print(nova_frase)
frase_separada = frase.split()
print(frase_separada)
print(frase_separada[0])
print(frase_separada[1])
print(frase_separada[2])
print(frase_separada[3])
print(frase_separada[4])

indice0 = frase.find('Estruturas')
indice1 = frase.find('de')
indice2 = frase.find('Dados')
indice3 = frase.find('em')
indice4 = frase.find('Python')
print(f'Indice da palava {frase_separada[0]}: {indice0}')
print(f'Indice da palava {frase_separada[1]}: {indice1}')
print(f'Indice da palava {frase_separada[2]}: {indice2}')
print(f'Indice da palava {frase_separada[3]}: {indice3}')
print(f'Indice da palava {frase_separada[4]}: {indice4}')
